name: first CI/CD Pipeline

on:
  push:
    branches:
      - main

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Print message
        run: echo "Hello, this is the first CI/CD pipeline!"

      # Step 2
      - name: Print another message
        run: echo "Hello, this is the first CI/CD pipeline!"